apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mmv3ls70b-python
  janus-idp.io/tekton: mmv3ls70b-python
  backstage.io/kubernetes-id: mmv3ls70b-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mmv3ls70b-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
